import { Bell, CheckCheck } from 'lucide-react';
import { NotificationPanel } from '../components/simulation/NotificationPanel';
import { useSystemState } from '../context/SystemContext';

export function NotificationsPage() {
  const { notifications } = useSystemState();
  const unreadCount = notifications.filter((n) => !n.read).length;

  return (
    <div className="animate-fade-in max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold font-display text-navy-900">Notifications</h1>
          <p className="text-navy-500 mt-1 text-sm">
            {unreadCount > 0 ? `${unreadCount} unread notification${unreadCount > 1 ? 's' : ''}` : 'All caught up'}
          </p>
        </div>
        <div className="w-12 h-12 rounded-xl bg-medical-50 flex items-center justify-center relative">
          <Bell className="w-6 h-6 text-medical-600" />
          {unreadCount > 0 && (
            <div className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-danger-500 text-white text-[10px] font-bold flex items-center justify-center">
              {unreadCount}
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center justify-end mb-4">
        <button className="flex items-center gap-1.5 text-xs text-medical-600 font-medium hover:text-medical-700 transition-colors">
          <CheckCheck className="w-3.5 h-3.5" />
          Mark all as read
        </button>
      </div>

      <NotificationPanel />

      <div className="mt-6 p-4 rounded-xl bg-gray-50 border border-gray-100">
        <p className="text-xs text-navy-400 leading-relaxed text-center">
          Notifications are generated by the MS.care system during care cycles. In a production environment,
          these would be delivered to the caregiver's device in real time.
        </p>
      </div>
    </div>
  );
}
